### ISSUE TITLE
Other RSS feeds?

### ISSUE THREAD

**Issue by TPBT-OFFICIAL** [nicoboss/KickassCopy#2]
Would it be possible to add other rss feeds? for example isohunts one: http://isohunt.to/rss/rss.xml

**Comment by TPBT-OFFICIAL** [comment]
Ok i think its already done i didn't notice so i feel a little stupid.... are all these scripts working perfecly?

**Comment by nicoboss** [comment]
Yes it’s possible and I’ll bring the iso hunt feed to work next few days. Thing is that my updater not support xml feeds at the moment. It wouldn’t be a lot of work to implement this. I only have to copy & paste the rss thing and edit it a little bit. It’s possible to use more than one feet at the same time by opening different scripts.

**Comment by TPBT-OFFICIAL** [comment]
@nicoboss it would be nice if you could do that as im not that good with these things :)

**Comment by nicoboss** [comment]
I did it. It was much more complicated than I thought. You are right IsoHunt is in the RSS format but they made their own torrent standard, that wasn’t made for getting single data because they write nearly everything in the description. So I had to rewrite a lot of my program. I also decided to make for every famous torrent RSS feed a database updater that you can use without any problems together on one server. The IsoHunt updater has a refresh time of 20 minutes because it doesn't make sense to  update it more frequently because it shows the last 100 uploads and there are approximately 100/3h so 11 new files per 20 minutes. The Kickass one gives approximately 20 per 5min so if you only use one it's better to use the Kickass one but to use both is the best. Both get exactly the same amount of additional torrent data. The next RSS updater I’ll do is maybe the BitSnoop one but the most important thing now is to make a high quality database with over 20 000 000 Torrents including their descriptions.

**Comment by nicoboss** [comment]
https://guides.github.com/features/mastering-markdown/
